Document: neurosim
Title: Debian neurosim Manual
Author: <insert document author here>
Abstract: This manual describes what neurosim is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/neurosim/neurosim.sgml.gz

Format: postscript
Files: /usr/share/doc/neurosim/neurosim.ps.gz

Format: text
Files: /usr/share/doc/neurosim/neurosim.text.gz

Format: HTML
Index: /usr/share/doc/neurosim/html/index.html
Files: /usr/share/doc/neurosim/html/*.html


